### ISSUE TITLE
emulationstation setup - no controllers detected

### ISSUE THREAD

**Issue by meav33** [mholgatem/GPIOnext#11]
Hello, i'm building a raspberry handheld and want to use buttons conneced to gpio pins as input in retropie.
I succesfully added them in the gpionext config and they work when i type gpionext test 1.
But i cannot get them to setup in retropie.
The emulationstation setupscreen only shows "No gamepads connected." and holding or pressing buttons does no difference. If i connect a usb keyboard, the usb keyboard works, but the gpio buttons are still not recognised.

How can i get the virtual joystick to work in retropie?

**Comment by mholgatem** [comment]
just type:
```
gpionext reload
```
and that should get it working.

**Comment by meav33** [comment]
Thanks,i got it to work now
