### ISSUE TITLE
A physical pull up resistor is fitted on this channel!

### ISSUE THREAD

**Issue by dotmick** [mholgatem/GPIOnext#13]
Hi there,

I am currently facing a problem that makes my GPIOnext not working. But it was yesterday :/

Here are the pins I am using 3,5,7,8,9,12,31,33,35,36,37,40.

And the message I do get:

> May 18 18:22:14 retropie systemd[1]: Started gpionext-daemon.
> 
> May 18 18:22:17 retropie python3[10706]: /home/pi/GPIOnext/config/gpio.py:55: RuntimeWarning: A physical pull up resistor is fitted on this channel!
> 
> May 18 18:22:17 retropie python3[10706]:   GPIO.setup(number, GPIO.IN, pull_up_down=pull)
> 
> May 18 18:22:17 retropie python3[10706]: Traceback (most recent call last):
> 
> May 18 18:22:17 retropie python3[10706]:   File "gpionext.py", line 116, in <module>
> 
> May 18 18:22:17 retropie python3[10706]:     GPIOnext( args )
> 
> May 18 18:22:17 retropie python3[10706]:   File "gpionext.py", line 54, in __init__
> 
> May 18 18:22:17 retropie python3[10706]:     gpio.setupGPIO( self.args )
> 
> May 18 18:22:17 retropie python3[10706]:   File "/home/pi/GPIOnext/config/gpio.py", line 99, in setupGPIO
> 
> May 18 18:22:17 retropie python3[10706]:     pins.append( pin(pinNumber, pull, args) )
> 
> May 18 18:22:17 retropie python3[10706]:   File "/home/pi/GPIOnext/config/gpio.py", line 55, in __init__
> 
> May 18 18:22:17 retropie python3[10706]:     GPIO.setup(number, GPIO.IN, pull_up_down=pull)
> 
> May 18 18:22:17 retropie python3[10706]: ValueError: The channel sent is invalid on a Raspberry Pi
> 
> May 18 18:22:18 retropie systemd[1]: gpionext.service: Main process exited, code=exited, status=1/FAILURE
> 
> May 18 18:22:18 retropie systemd[1]: gpionext.service: Unit entered failed state.
> 
> May 18 18:22:18 retropie systemd[1]: gpionext.service: Failed with result 'exit-code'.
> 
> May 18 18:22:19 retropie systemd[1]: gpionext.service: Service hold-off time over, scheduling restart.
> 
> May 18 18:22:19 retropie systemd[1]: Stopped gpionext-daemon.

Any idea why?

Thanks!

**Comment by mholgatem** [comment]
The "physical pull up resistor is fitted on this channel!" is just a warning that pops up when you use pins 3 or 5, it's nothing to worry about.
The problem is that pin 9 cannot be used as it is a ground.

**Comment by dotmick** [comment]
@mholgatem yep, you're right. I've made a mistake and it should be 10 instead of 9.

Thanks for pointing that out!

**Comment by mholgatem** [comment]
no problem
