### ISSUE TITLE
install.sh does nothing

### ISSUE THREAD

**Issue by joelastley555** [mholgatem/GPIOnext#15]
Upon typing in "bash GPIOnext/install.sh", it does nothing. No messages no nothing. Just goes back to prompt immediately.

**Comment by mholgatem** [comment]
That's weird. Check to make sure that it got cloned correctly (make sure there is actually something in the file).

`nano ~/GPIOnext/install.sh`

if it's empty. Delete everything and start over

```
sudo rm -r ~/GPionext
cd ~
git clone https://github.com/mholgatem/GPIOnext.git
bash GPIOnext/install.sh
```

if it's not empty, try running it as root:

`sudo bash ~/GPIOnext/install.sh`
