### ISSUE TITLE
Python scripts through commands option

### ISSUE THREAD

**Issue by julenvitoria** [mholgatem/GPIOnext#20]
Hello, first of all thanks in advance. I would like to know if it is possible to execute a Python script through the command option in gpionext. I tried to run with "sudo python /home/pi/script.py" and it did not work but if I execute a normal command I can make it work. I do not know if it's because gpionext is not designed to run Python scripts or if I'm doing something wrong.

Thanks

**Comment by mholgatem** [comment]
yes, you can run a python script just like that. Check to make sure that you have made the script executable ( chmod +x /home/pi/script.py ). Also check to make sure that there are no errors in your script, as it won't alert you if the script exits prematurely from an error. If you are still having problems, you can post a link to your script and I'll take a look.
