### ISSUE TITLE
Attempting to use GPIOnext causes restart

### ISSUE THREAD

**Issue by mking42** [mholgatem/GPIOnext#21]
Trying to use gpionext causes a restart every time.
Tried:
1. gpionext config
2. sudo python3 /home/pi/GPIOnext/config_manager.py
3. gpionext config --pins 36,38,39,40
4. gpionext stop
5. any other gpionext command

Switching to and running commands as root user still results in the same behaviour.

Any attempt at using GPIOnext results in a restart of the system.

I am using the latest Raspbian Stretch based RetroPie image (4.4).
Hardware: Raspberry Pi 3 B

**Comment by mking42** [comment]
Apart from the default package install I also updated the Retropie setup script and underlying system packages.

I’m not sure if there may be a conflict with the powerblock? I haven’t had a chance to test without it yet.

**Comment by mholgatem** [comment]
it's almost certainly a conflict with the powerblock. Without having one to test with, I doubt that I will be able to troubleshoot it. 

Unless you have some specific other need for it, you don't need it for turning on and off your system. Just do this (you'll need to remove/uninstall your powerblock stuff first):

- Attach a button to pins 5 + 6. 
- type `gpionext config`
- select 'commands'
- select 'Add new command'
- `Enter a name for this command:` Shutdown
- press and hold your button
- `Enter a command to map to this button:` gpionext stop; sudo shutdown -h +1 "System shutting down in 1 minute!"
- `map additional commands to this button?` n
- Exit
- `gpionext start`

This will run the shutdown script whenever the button has been pressed and the system is on. When the system is off, pin 5 has the unique ability to wake the system up and restart it. so simply shorting it with any ground pin will restart your system.

**Comment by mholgatem** [comment]
yes, sorry if it wasn't clear; but that is what the above directions do. The button connected to pin 5 will be able to wake and shutdown the system, all in one.

There probably is some way to resolve the conflict with the powerblock, if you are so inclined. But without one for me to test on, it would be a slow process on my end. Hopefully this solution gets you up and running though!
