### ISSUE TITLE
GPIOnext Pull Down

### ISSUE THREAD

**Issue by Prochip121** [mholgatem/GPIOnext#31]
Hi, 
A little background, I initially set up GPIOnext on a Pi Zero without any issues however I noticed when any button was held the PWM audio out would stop and would only resume after the key was released. I thought I would try to see if switching to Pull Down switches solved this issue. However, I have run into an issue when using the GPIOnext pull-down flags. I'll try to explain as best as I can. I have installed a completely fresh RetroPie and have installed both WiringPi and GPIOnext. I have simplified the project to a singular GPIO input as shown below:

![Wiring](https://user-images.githubusercontent.com/51718408/59297255-bbbd6e80-8c7f-11e9-8467-bc89d931b411.jpg)

In the boot config:

`Sudo nano /boot/config.txt`

I have changed the pin state by adding the line:

`gpio=_PIN_=ip,pd` 

Then by running the `gpio read 28` I was able to confirm that that pin was indeed correctly set to pull down. "Reading 0 when released and 1 when pressed". 

I then configured GPIOnext to use the pull down flags using:

`gpionext set pulldown true`
`gpionext reload`

So far so good, using `gpio read 28` the pin was still reading correctly. The next stage was to configure the button in GPIOnext using:

`gpionext config`

To keep things simple as possible I configured joystick 1 with 0 Dpads and only one button selected, in this case button "A". After proceeding I enter the configure Joypad 1 page where I am instructed to Hold the button. The button, however, is not detected in this stage. 

When I exit the gpionext configuration page I then try the wiringpi command 

`gpio read 28`

Now the pin state has inverted and is now reading as 1 instead of 0. It seems when entering gpionext config reverts the changes made above to the pin back to the original pull up state.

I've tried to explain as detailed as possible and am quite new to this so if I have missed something let me know and I'll try to add it. It's probably something simple that I have missed but any assistance would be appreciated. 

Thanks!

Kind Regards,
George

**Comment by mholgatem** [comment]
so the "set" command only adjusts the systemd (systemctl) file. It has no bearing on when the config file is run. all that you need to do is run `gpionext config --pulldown` and you should be good to go.
