### ISSUE TITLE
Can GPIOnext run on an Asus Tinkerboard?

### ISSUE THREAD

**Issue by fordy76** [mholgatem/GPIOnext#36]
Hi,

I have Retropie running on an Asus Tinkerboard and I've tried to install GPIOnext, I have run into a few install issues and now seem to have hit a brick wall running gpionext config. I get an error with the RPi.GPIO module, it only runs on a Raspberry Pi. Do you know of any work around?

Thanks

**Comment by mholgatem** [comment]
sorry, short of writing your own gpio module for tinkerboard, I don't know of any drop in replacements for RPi.GPIO
