### ISSUE TITLE
EmulationStation not recognising GPIOnext config?

### ISSUE THREAD

**Issue by edwardcox** [mholgatem/GPIOnext#37]
Sorry, newb here so please feel free to ask questions of me.
Raspberry PI 3 B, GPIOnext joypad, Arcade Game, Power Control System (Jaycar XC9062 and XC9064). Using current RetroPie build. 
Steps taken:
Boot ok, 
launches into EmulationStation, 
press F4, as per included 1 page instruction; 
sudo apt update, 
sudo apt install git python3-dev -y, 
git clone blah GPIOnext.git, 
sudo ./install.sh
Follow all prompts to setup joystick, buttons, etc
gpionext test 1
All results seem correct and successful.
launch EmulationStation, Welcome screen, 1 Gamepad detected.
As soon as I press any key to configure device, “GPIOnext Joypad 1” on screen with “OK” below and that’s it. Nothing progresses except F4.

Please, pulling what’s left of my hair out, have honestly searched multiple forums, no close results.

Thank you kindly,

Ed.

**Comment by mholgatem** [comment]
Forgive be, it's been a while since I've set up the controllers, but I
think that you have to press and hold a button. I can't remember if it's a
specific button or just any button.

-Mark
