### ISSUE TITLE
wont work at all

### ISSUE THREAD

**Issue by EpicPandaGamer** [mholgatem/GPIOnext#38]
I instlal the git repo to my retropie build and I have a breadboard with a few buttons on just to test these buttons are 100% wired correctly i run the install.sh and all is good i then config all is good I run gpionext start all is good I go to emulation station my buttons dont work so i reboot my system they still dont work so i reconfig I do that 5 times .

**Comment by mholgatem** [comment]
You need to configure the controller in the emulation station setup. Be aware, that emulation station doesn't auto recognize a controller unless it has a directional pad and, I believe, 2 buttons (it may be more). You can configure a controller manually by directly writing to a config file, though I don't have a setup available to me at the moment, so I wouldn't be able to walk you through that.
