### ISSUE TITLE
Joystick Issue

### ISSUE THREAD

**Issue by Walli1223334444** [mholgatem/GPIOnext#44]
I wired up some buttons and a joystick. When I try to configure the joystick it doesn’t not recognise it when I hold it down or right even though it finds the pins when I hold up and left. Otherwise there haven’t been any issues.

**Comment by pieter16** [comment]
Same issue here. Recalbox sees my 2 joysticks and 17 buttons, therefore it’s not a hardware issue. With retropie, GPIOnext will see everything but the down on my joystick1 - pin 11. No idea on how to solve that :(

**Comment by mholgatem** [comment]
If it worked in recalbox, then the issue lies in retropie. I would guess that retropie has some module that is being activated and is grabbing that pin so that gpionext can't use it. Perhaps a touchscreen module or controller module?

**Comment by pieter16** [comment]
Thanks for your answer, and for your great job. I wasn't clear enough sorry: my hardware was recognised directly by RecalBox with the embedded driver (mkjoystickarcade), not GPIOnext. Btw, for additional information I'm using a RPI4. Will try again a fresh install of Retropie with GPIOnext.

**Comment by Cazna52** [comment]
Hi. I am having the same issue with GPIOnext. Which file/s could I check to see if other modules are taking pins?
