### ISSUE TITLE
Run commands

### ISSUE THREAD

**Issue by nasp2000** [mholgatem/GPIOnext#45]
Hi all

I have used gpionext it great sucess and most it simple programmable buttons like:
 sudo halt 
or volume+ or down:
/usr/bin/amixer -q -c 1 sset Headphone 4dB- unmet no cap

But now i am stuck it running scripts, for example "/home/pi/screen.sh",  programmable with or without sudo it full paths and the script simple don´t run. The script are mark it executable and i test the script first running  ./screen.sh.

What is wrong ? How i put the script working it a button from gpionext...

**Comment by mholgatem** [comment]
You need to specify the direct path to your bash interpreter. It should be something like `/bin/bash /home/pi/screen.sh`

**Comment by nasp2000** [comment]
Half easy the solution.... i tried to run like /bin/bash /home/pi/screen.sh but don´t work. Only works it user pi
like this:
su -c "/bin/bash /home/pi/screen.sh" pi

**Comment by mholgatem** [comment]
I think that if you create a group and add root and the file to the group, it should work.
```
groupadd gpionext
usermod -a -G gpionext root
chown :gpionext /home/pi/screen.sh
```
(create the group gpionext
add root to the gpionext group
change the group-owner of /home/pi/screen.sh to gpionext)
