### ISSUE TITLE
two player configuration for Retropie

### ISSUE THREAD

**Issue by ooskay** [mholgatem/GPIOnext#47]
Hi,
Is there have any way to configure second player/joyistik? So, i needed like two different keyboards emulation at the same service. Thanks..

**Comment by mholgatem** [comment]
You can do up to 4 virtual gamepads but only 1 virtual keyboard. Using emulationstation/retropie you can map the keys from 1 virtual keyboard to 2 (or more) separate controllers

**Comment by ooskay** [comment]
Thanks for swift respond. 1 Virtural Keyboard and 1 Joyistik would be enought.. best..
