### ISSUE TITLE
Raspberry pi 3 --  RPi.GPIO error

### ISSUE THREAD

**Issue by Tailslide** [mholgatem/GPIOnext#48]
Install Complete!
Would you like to run the configuration manager now? [y/n]Install Complete!
Would you like to run the configuration manager now? [y/n]y
Traceback (most recent call last):
  File "/home/pi/GPIOnext/config_manager.py", line 15, in <module>
    from config import gpio, menus, SQL
  File "/home/pi/GPIOnext/config/gpio.py", line 2, in <module>
    import RPi.GPIO as GPIO
RuntimeError: This module can only be run on a Raspberry Pi!
-------------> Setup Complete!

**Comment by Tailslide** [comment]
This solved it for me:

sudo apt-get purge python{,3}-rpi.gpio
sudo -H pip2 install --upgrade pip
sudo -H pip3 install --upgrade pip
Install RPi.GPIO from updated pip:

python -m pip install RPi.GPIO
python3 -m pip install RPi.GPIO

**Comment by Devenhulk123** [comment]
Hey I have sorta the same problem and I'm wondering if you could help me this is what it says 
![20230720_125600](https://github.com/mholgatem/GPIOnext/assets/140114198/48495006-5a86-441c-a683-3e11b5da78cb)
I copied an
![20230720_125550](https://github.com/mholgatem/GPIOnext/assets/140114198/d2554aca-6f46-451d-921d-4fc8f9c8a3ba)
D pases these codes
