### ISSUE TITLE
Doesn't detect GPIO pins 0 and 1.

### ISSUE THREAD

**Issue by rubencg195** [mholgatem/GPIOnext#49]
when running the gpio-next program, everything goes well but it fails to recognize pins 0 and 1.

**Comment by mholgatem** [comment]
sorry, I am unsure as to what you are referring. There is no pin 0; pin 1 is strictly 3.3v (no input). If you are referring to gpio #, gpio 0 only exists on legacy Raspberry pi 1 Rev 1, which I don't have access to, so I can't test that. If you are continuing to have troubles, please reach out and I'll do my best to help.
