### ISSUE TITLE
Config tool not seeing gpio even though its working

### ISSUE THREAD

**Issue by Tailslide** [mholgatem/GPIOnext#51]
So I was able to wire up and successfully configure a joystick and buttons with GPIOnext with the config wizard.

Now, I wired up a second joystick and I can't reconfigure anything.. I get to the part where it wants me to hold the joystick UP and it doesn't recognize the switch.  The strange thing is this same joystick is still working fine in retropie as a joystick device.

I tried checking the GPIO pins with the gpio command and they are showing as triggered there just fine.
I tried running the remove script and the GPIOnext folder and reinstalling from scratch, same issue.

Really not looking forward to reinstalling retropie from scratch again :(

---
Update.. I have a pin ouput I use to control the lights on my cabinet.. seems to confuse the config utility in GPIOnext. Workaround of unplugging that pin during configuration solves the problem.

**Comment by mholgatem** [comment]
The lights were probably pulling your pins high, would be my guess. Glad you were able to figure it out.
