### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tmddn3070** [mholgatem/GPIOnext#52]
![image](https://user-images.githubusercontent.com/69005921/128585335-c3c5075a-c302-4f03-ac92-d35f97867591.png)
I'm trying to install, but this error pops up, what should I do?

**Comment by mholgatem** [comment]
sorry, I've been unavailable for a while. That error means that it can't access your gpio pins. There's probably something else accessing them first. This is pretty old, so I'm going to close this issue, but if you are still having problems, you can still comment and I'll try to help you out.
