### ISSUE TITLE
EvDev not Found

### ISSUE THREAD

**Issue by aliyahqayum** [mholgatem/GPIOnext#57]
## Module Not Found Error

After trying to configure GPIO pins using GPIO next, we are getting an error that the EvDev module is not found. What can we run to ensure all modules have been downloaded?

![D4AFC02C-6780-43B7-9FF9-AF85939CF86F](https://user-images.githubusercontent.com/86263422/136246921-6ff9750e-1ce7-4054-814c-a470f90cfbe6.jpeg)

**Comment by merwok** [comment]
I think instructions are here: https://github.com/mholgatem/GPIOnext#how-to-install 
There is a script that does everything (or can be read to do equivalent steps).

**Comment by aliyahqayum** [comment]
> I think instructions are here: https://github.com/mholgatem/GPIOnext#how-to-install
> There is a script that does everything (or can be read to do equivalent steps).

Right but we are getting this issue when cloning the repository. What is the script that does everything?

**Comment by aliyahqayum** [comment]
When we are trying to clone the repository, we are getting an error:

`Unable to acess (repo link): Could not resolve host github.com`

From the two years we've been using this, we never had an issue come up like this. 

We were getting the above error when trying to clone an evdev repo. Should we be setting gpionext set dev to true?

**Comment by mholgatem** [comment]
By the looks of it, this is after you've already cloned the repository and are now trying to run gpionext. It looks like either evdev didn't install correctly or it didn't get added to the modules list.

First, check to see if evdev is installed
`sudo pip3 install evdev`

if that is installed, you next want to check to make sure the module is getting loaded.
`sudo nano /etc/modules`
if *evdev* is not listed, add it on it's own line at the end of the file. save and exit.

reboot and hopefully you are up an running. If not, come back with any errors that you are getting. I probably won't check back until Monday at the earliest though.

**Comment by aliyahqayum** [comment]
When running 

`sudo pip3 install evdev`

We found that we didn't have python installed. We attempted to install it using: 

`sudo apt install python3-pip`

But the retropi doesn't have enough space to download all the packages. We tried installing python 2.7 instead, but that didn't work either.

**Comment by aliyahqayum** [comment]
Still taking up too much space :( 
We need more than 2kb but we only have 16gb
