### ISSUE TITLE
No module named evdev

### ISSUE THREAD

**Issue by Jackslayerr** [mholgatem/GPIOnext#60]
I’ve been trying to get GPIOnext working for hours and when I try to configure GPIOnext it says there’s no module names evdev. I’ve seen the issue posted multiple times in this project but I tried everything from all of them to try to fix this but nothing works. A couple things I’ve noticed was that while downloading something it said there was a error 404 link for the and that I was missing some things. I’ve also seen some people say a stock retropie version works, is that just an older version? Because I tried to use and older version but it didn’t work.

**Comment by merwok** [comment]
> while downloading something it said there was a error 404 link

> I was missing some things


Please give useful details to make bug reports actionable!
What commands you types, what full error message you got.

**Comment by Jackslayerr** [comment]
> > while downloading something it said there was a error 404 link
> 
> > I was missing some things
> 
> Please give useful details to make bug reports actionable! What commands you types, what full error message you got.

Thanks for the Reply! I got the error running the command
“sudo apt install python-pip” in an attempt to fix the issue. Here’s the output, towards the bottom is where it gives me the 404 error

![198152A0-C2C5-45CC-A87D-B765D1D4AB37](https://user-images.githubusercontent.com/91853627/147884512-50c1c491-5a0b-480c-a93a-ab0d39049d14.jpeg)

**Comment by merwok** [comment]
Have you tried one of the two suggestions in the last line of the error message?

**Comment by Jackslayerr** [comment]
The first suggestion didn’t do anything because apparently my access was denied and I didn’t understand the second suggestion.

![4056BA45-DD13-437A-9833-01B063D9BA79](https://user-images.githubusercontent.com/91853627/147885053-efade7e4-921f-4902-b3a6-39f34bdd9127.jpeg)

**Comment by merwok** [comment]
You have to run system administration commands as root (using sudo)

**Comment by Jackslayerr** [comment]
Ok that time it worked (Sorry I’m a bit a new to this stuff) I’m still getting that 404 message when trying to install python. What was the second suggestion?

**Comment by merwok** [comment]
Can you show that error message?

**Comment by Jackslayerr** [comment]
> Can you show that error message?

![6B22BBBA-3E65-4575-814D-0F72CBCA5DF1](https://user-images.githubusercontent.com/91853627/147886358-9c2bf0d5-1f60-4135-ba52-759fa7cda87f.jpeg)

**Comment by merwok** [comment]
Actually, there is an `install.sh` script in this repo that does apt update and more — can you use it?

**Comment by Jackslayerr** [comment]
> Actually, there is an `install.sh` script in this repo that does apt update and more — can you use it?

I thought I tried it but what’s the command?

**Comment by merwok** [comment]
It is an executable script, so `./install.sh`

**Comment by Jackslayerr** [comment]
This is what I got 

![465589B7-3C7B-4696-A609-BEF90AD9B779](https://user-images.githubusercontent.com/91853627/147888166-71a91003-a6dc-4865-a51c-eb2588bdfb8b.jpeg)

**Comment by merwok** [comment]
It’s in the gpionext repository, so you have to run that command from your clone of it

**Comment by Jackslayerr** [comment]
> It’s in the gpionext repository, so you have to run that command from your clone of it
> Follow https://github.com/mholgatem/GPIOnext#how-to-install

I’ve tried everything but still nothing. I heard someone say they just got a stock version of Retropie. What other image could I get?

**Comment by Jackslayerr** [comment]
So I was able to finally get it working. I went and updated Retropie within the OS and a bunch of stuff downloaded and I tried GPIOnext again and it worked! I hope I helped other people with this issue.

**Comment by mholgatem** [comment]
Hey, I'm glad that you were able to get it working. Sorry I was unavailable for the last week.

For anyone that comes across this problem in the future, my guess would be that the Debian/Ubuntu distribution that your retropie image used was old. Ubuntu gives it's releases a shelf life. After that, it migrates its packages to a new location to ensure that you aren't mixing old releases with new. You can typically fix this by updating the current distribution using the following command:

`sudo apt-get dist-upgrade`

or you can update your packages list with the new sources by editing:

`/etc/apt/sources.list`

Happy Gaming!

**Comment by naenaejeff** [comment]
its not working for me, and that file is read only, im not sure how to edit it? any help?

**Comment by merwok** [comment]
To get help, you need to say what you did (copy the exact command) and what you got (copy the full error message)
Otherwise you are asking for mind reading 😅

**Comment by Billardgates** [comment]
ive done everthing updated retro pi and re download retro pi as a whole but nothing. it sill gives me this error after i clone the GPIOnext files and install. it gives me quite a few errors -> [every time it tries to download an asset from http://raspian.raspberrypi.org/raspbian buster/main armhf (asset name)] not found messages while downloading. but then it says install complete would you like to run the configuration manager now? yes then it spits back this 
traceback (most recent call last):
  File "/home/pi/GPIOnext/config_manager.py", line 14, in <module>
     from evdev import ecodes as e
ModuleNotFoundError: No module named 'evdev'

im 99% sure it the raspian download errors that are my problem 
what does that mean and how can i fix it?
