### ISSUE TITLE
Unable to use GPIO 0 

### ISSUE THREAD

**Issue by sunxianrun1** [mholgatem/GPIOnext#62]
I used to map gpio 0 (SDA.0) to ‘up’ with [mk_arcade_joystick], which is not that powerful as Gpionext, on pi0. But when trying Gpionext, it won’t work as gpio 0 can’t be detected. I don’t want to modify the hardware. Please help to make the gpio 0 able to work. Thx a lot(●°u°●)​ 」

**Comment by mholgatem** [comment]
Sorry about the lateness of this reply. That pin is not supported by rpi.gpio. I don't remember all of the specifics, but I believe that the system reserves it for communications with hats. They can be un-reserved and used, just not with rpi.gpio (hence, not with gpionext, which relies on rpi.gpio). Sorry that this isn't more helpful!

for future reference, here's a list of all available physical pin #'s that can be used with gpionext


```
--  --
03  --
05  --
07  08
--  10
11  12
13  --
15  16
--  18
19  --
21  22
23  24
--  26
--  --
29  --
31  32 
33  --
35  36
37  38
--  40

```
