### ISSUE TITLE
Configuration not saving 

### ISSUE THREAD

**Issue by Jackslayerr** [mholgatem/GPIOnext#72]
When I try to make a configuration for Joypad 1 it says It’s saving the configuration but when I run a test it says it’s nothing. I have 1 D-Pad and 4 other buttons. I use gpionext config —pulldown to configure the buttons. Any reason why it’s not working? I use a Raspberry PI 4 with the latest version of Retropie. This has worked for me in the past I don’t know what happened.

**Comment by mholgatem** [comment]
Did you set the pulldown flag for the gpionext daemon?
`gpionext set pulldown true`

Otherwise, as stated in your duplicate issue #67, you need to get me a copy of your config file. It's the only way that I can troubleshoot.
