### ISSUE TITLE
install.sh can't run without internet

### ISSUE THREAD

**Issue by elaxius** [mholgatem/GPIOnext#74]
Currently the installer requires the internet to install various packages. Is it possible to provide it as part of the git folder itself so that i can install it on raspberry pi 0 (without W)

**Comment by fedekrum** [comment]
I understand your problem, but I think the reason for this is that gpionext has to be installed from internet too and that doing so will implied the author to be maintaining this package itself if some other package is updated.  In the install.sh script, you can see which packages are necessary.

```
sudo apt-get -y install python3 python3-pip python3-dev gcc
sudo apt-get -y install sqlite3 joystick
sudo apt-get install python3-rpi.gpio
sudo pip3 install evdev
```

Manually install those packages first, and then erase those lines when you run the install.sh.

**Comment by mholgatem** [comment]
sorry @elaxius, that's outside of the scope of this project. As @fedekrum pointed out, you can download the packages and remove them from the installer on a one off basis.
