### ISSUE TITLE
RetroPie Not Recognizing New Gampad

### ISSUE THREAD

**Issue by vogtjame** [mholgatem/GPIOnext#76]
Hello,

I have configured a new gamepad using gpionext config and was able to get all the way through the config process with no issues. However, when I do "gpionext start" and then reboot, retropie is unable to detect a new gamepad. Any advice on this issue?

**Comment by mholgatem** [comment]
RetroPie can be picky if there aren't enough buttons registered.  Can you
describe your controller?

**Comment by vogtjame** [comment]
Ah that is the problem then. I wired up only 4 buttons just to test. I see the previous thread now where you said it needs at least one directional pad and two buttons to work. When I tried that, it works. Thanks for the quick response!
