### ISSUE TITLE
Install fails as per Jaycar instructions. Help. :)

### ISSUE THREAD

**Issue by glenhendry** [mholgatem/GPIOnext#77]
I can't install it using the instructions as it asks for username and password credentials and then fails because password authentication has been removed on aug last year?

**Comment by mholgatem** [comment]
3 things (also, screenshots usually help):

What is asking for username and password?

What Raspbian release are you on?
Type `lsb_release -c` to find out.

Are you running as a user that has sudo privileges?
Type `getent group sudo` and check if your current username is listed in the output.

**Comment by glenhendry** [comment]
![20230102_100231_HDR.jpg](https://user-images.githubusercontent.com/121328859/210188025-b33c89f1-60f8-4ee4-9f98-2185533ebc92.jpg)

![Screenshot_20230102-095825.png](https://user-images.githubusercontent.com/121328859/210188039-4ef681d8-da62-4c9a-afe1-d6bd65a45f5d.png)

Thanks for the clarifying questions. Sorry for the lack of detail.

Attached is the credentials request from the git clone and the answers to your other questions.

Thanks so much for your help.

Glen

**Comment by mholgatem** [comment]
ah, I see the problem. You have a misspelling in the git address.
you added an extra 'e' in mholgatem
it should be `git clone https://github.com/mholgatem/GPIOnext.git`

**Comment by glenhendry** [comment]
Thanks! This fixed it. You're sw and help us appreciated.

**Comment by mholgatem** [comment]
No problem!
