### ISSUE TITLE
device selection not working in config menu

### ISSUE THREAD

**Issue by djanben** [mholgatem/GPIOnext#8]
I installed _gpionext_ on retropie 4.3 on a raspberrypi 3.
I can navigate up and down in the config menu, but the item selection does not work.
Nothing happens on pressing ENTER or SPACE or the like.
I cannot exit either - had to cancel with CTRL+C.
I was logged in via _ssh_.
Unfortunately, I don't see a manual way for configuring _gpionext_.

**Comment by mholgatem** [comment]
First off, what type of keyboard are you using? is it a standard keyboard or like a mini-wireless keyboard? 
Second, if you are using a standard keyboard, are you pressing the _Enter_ that is on the keypad, or the one that is just above _right shift_?

**Comment by djanben** [comment]
Sorry, for the late reply. The github mails had been filtered out as spam.
I was logged in to the raspberrypi from my laptop via _ssh_.
The laptop's keyboard does not have a number keypad.
I was using the normal ENTER key above right-shift.
I had also tried to change _process_user_input()_ in _curses_menu.py_ to check for _curses.SPACE_ or _curses.ENTER_ rather than _ord('\n')_ - without success.
In the meantime I have removed gpionext and installed gpioneer and configured it via the web interface.

**Comment by mholgatem** [comment]
hmm... ok. which ssh program and OS are you using on your laptop? I'll see if I can replicate the problem that you are running into.

**Comment by djanben** [comment]
I'm using [Solus Linux](https://solus-project.com) with OpenSSH_7.6p1, OpenSSL 1.0.2n  7 Dec 2017.
I could probably switch back to gpionext and do some more tests on that.
However, as far as I can see, there is no debug output from the configuration menu.

**Comment by djanben** [comment]
After adding some debug output I found out that the key code for ENTER is 343 which equals curses.KEY_ENTER. This seems to make sense. Please consider my corresponding pull request.

Nice work, by the way :-)

**Comment by mholgatem** [comment]
ok, lets give this a shot if you don't mind. 
in curses_menu.py change line 321 from this:

`		elif user_input == ord("\n"):`

to this:

`		elif user_input = curses.KEY_ENTER or user_input == 10 or user_input == 13:`

apparently curses can receive several different values for enter depending on the terminal. I was under the impression that _ord('\n')_ handled them all, but it doesn't. Hopefully this will solve the problem. If it does, I'll make the changes in the main repository.

**Comment by djanben** [comment]
I already made that change and tested it successfully. Plesse see my pull request. I have made that change in three menu files.

**Comment by mholgatem** [comment]
I just saw your changes. I'll take care of it. Thanks for taking the time to test troubleshoot this with me. Let me know if there are any other problems.
