### ISSUE TITLE
Gpio next syntax error raspberry pie 3 emulation station

### ISSUE THREAD

**Issue by Devenhulk123** [mholgatem/GPIOnext#83]
I wanted to use my raspberry gpio pins and I installed it using these scripts 
cd ~
git clone https://github.com/mholgatem/GPIOnext.git
bash GPIOnext/install.sh
After that that it gave me a invalid syntax 
I dont know what to do or what I put to set a input really. This is the invalid syntax it gives me
![20230720_154401](https://github.com/mholgatem/GPIOnext/assets/140114198/a23a7125-2833-485d-acb7-c8bf6f3e9df6)

Thanks 
Deven

**Comment by merwok** [comment]
Hello!  To get help with a problem on the internet, you need to say
- what command you run
- what error message you see (preferably as text not screenshots)

**Comment by Devenhulk123** [comment]
> Hello! To get help with a problem on the internet, you need to say
> 
> * what command you run
> * what error message you see (preferably as text not screenshots)

Sorry Its my first time posting so I didn't really know what to put

**Comment by mholgatem** [comment]
The reason that you are getting that error is that you are most likely running an old version of python3. Use this command to find your version:

`python3 --version`

**Comment by Devenhulk123** [comment]
> The reason that you are getting that error is that you are most likely running an old version of python3. Use this command to find your version:
> 
> `python3 --version`
> 
> If your version is <3.6, upgrade it with: `sudo apt install python3.9`
I just tried and the same error popped up

**Comment by merwok** [comment]
That’s probably because the script uses `python3`, and on your system that corresponds to Python 3.6, even if 3.9 is installed.
Can you update your operating system to a version that uses a current Python version?

**Comment by Devenhulk123** [comment]
> That’s probably because the script uses `python3`, and on your system that corresponds to Python 3.6, even if 3.9 is installed. Can you update your operating system to a version that uses a current Python version?

I used sudo apt-get update followed by sudo apt-get upgrade  and everything thing is updated already what do you mean by upgrade the operating system?

**Comment by merwok** [comment]
Answering that would take some time, and be out of scope for this place!

But can you show the output of these commands:
```
cat /etc/os-release
apt-cache show python3 | head -n3
```

**Comment by Devenhulk123** [comment]
> Answering that would take some time, and be out of scope for this place!
> 
> But can you show the output of these commands:
> 
> ```
> cat /etc/os-release
> apt-cache show python3 | head -n3
> ```

Sorry for the late reply I went on a trip with my parents and we didn't have any signal if your still willing to help these are the stuff that popped up

**Comment by merwok** [comment]
Your link goes to this same page.
Can you copy-paste the output from the two commands?

**Comment by Devenhulk123** [comment]
> Your link goes to this same page. Can you copy-paste the output from the two commands?

pi@retropie:~$ cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)'

NAME="Raspbian GNU/Linux"

VERSION ID="9"

VERSION="9 (stretch)"

ID=raspbian

ID LIKE-debian

HOME URL="http://www.raspbian.org/"

SUPPORT URL="http://www.raspbian.org/RaspbianForums" BUG REPORT URL="http://www.raspbian.org/RaspbianBugs"

pi@retropie:~$ apt-cache show python3 | head -n3

Package: python3

Source: python3-defaults

Version: 3.5.3-1

pi@retropie:~ $

**Comment by Devenhulk123** [comment]
> Your link goes to this same page. Can you copy-paste the output from the two commands?

Sorry that was my bad

**Comment by merwok** [comment]
We learn two things:
- you are running raspberry pi OS 9, but the current version is 10
- the python version used by the `python3` command is 3.5, which is too old to support this script

Raspberry Pi foundation does not recommend updating the system in place, but making a fresh install on a new SD card.

**Comment by Devenhulk123** [comment]
> We learn two things:
> 
> * you are running raspberry pi OS 9, but the current version is 10
> * the python version used by the `python3` command is 3.5, which is too old to support this script
> 
> Raspberry Pi foundation does not recommend updating the system in place, but making a fresh install on a new SD card.

Is there any way I could try updating it without starting new SD card before I wipe it clean

**Comment by mholgatem** [comment]
Yes, you can. But in my experience, you tend to get better performance from a fresh install. If you are determined to just upgrade in place, [here's a guide](https://www.makeuseof.com/tag/raspberry-pi-update-raspbian-os/)

**Comment by Devenhulk123** [comment]
> Yes, you can. But in my experience, you tend to get better performance from a fresh install. If you are determined to just upgrade in place, [here's a guide](https://www.makeuseof.com/tag/raspberry-pi-update-raspbian-os/)

Okay thank you I'll try it out
