### ISSUE TITLE
unable to map 2 player controlls on the same controller

### ISSUE THREAD

**Issue by naenaejeff** [mholgatem/GPIOnext#85]
Hi again, Ive gotten everything to work now, but the software doesnt detect the 2nd player part of my arcade style controller. When i go to configure in retropie there isnt an option to map the second joystick ect. 
ive got 2 joysticks and 2 sets of select and start and 6 buttons for each player. am I doing somthing wrong or will I have to install github.com/recallbox/mk_arcade_joystick_rpi
as a work around. Im very new to all this raspberry pi stuff. Thanks in advance

**Comment by mholgatem** [comment]
you need to make sure that you have configured your arcade style controller as 2 separate controllers. If you have done that, you can test them by using the command `gpionext test 1` or `gpionext test 2` in order to test controllers 1 or 2, respectively.
